---

- name: Create the RKE2 config dir
  ansible.builtin.file:
    state: directory
    path: /etc/rancher/rke2
    owner: root
    group: root
    mode: 0755

- name: Set server taints
  ansible.builtin.set_fact:
    combined_node_taints: "{{ rke2_server_node_taints }}"
  when: rke2_type == 'server'

- name: Copy rke2 config
  ansible.builtin.template:
    src: "{{ rke2_config }}"
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: 0644

- name: Copy Containerd Registry Configuration file
  ansible.builtin.template:
    src: "{{ rke2_custom_registry_path }}"
    dest: /etc/rancher/rke2/registries.yaml
    owner: root
    group: root
    mode: 0644
  when: rke2_custom_registry_mirrors.0.endpoint | length > 0

- name: Restore etcd
  when: rke2_etcd_snapshot_file and ( "rke2-server.service" is not in ansible_facts.services )
  block:
    - name: Create the RKE2 etcd snapshot dir
      ansible.builtin.file:
        state: directory
        path: "{{ rke2_etcd_snapshot_destination_dir }}"
        recurse: true
        mode: 0755
    - name: Copy etcd snapshot file
      ansible.builtin.copy:
        src: "{{ rke2_etcd_snapshot_source_dir }}/{{ rke2_etcd_snapshot_file }}"
        dest: "{{ rke2_etcd_snapshot_destination_dir }}/{{ rke2_etcd_snapshot_file }}"
        mode: 0644
        force: true
    - name: Restore etcd from a snapshot
      ansible.builtin.shell: |
        rke2 server \
        --cluster-reset \
        --cluster-reset-restore-path="{{ rke2_etcd_snapshot_destination_dir }}/{{ rke2_etcd_snapshot_file }}" \
        --token {{ rke2_token }}
      register: task_output # <- Registers the command output.
      changed_when: task_output.rc != 0 # <- Uses the return code to define when the task has changed.

- name: Start RKE2 service on the first server
  ansible.builtin.systemd:
    name: "rke2-server.service"
    state: started
    enabled: true
    no_block: true
  environment:
    RKE2_TOKEN: "{{ rke2_token }}"

- name: Mask RKE2 agent service on the first server
  ansible.builtin.systemd:
    name: "rke2-agent.service"
    enabled: false
    masked: true

- name: Set an Active Server variable
  ansible.builtin.set_fact:
    active_server: "{{ inventory_hostname }}"
  run_once: true
