---

- name: Create the RKE2 config dir
  ansible.builtin.file:
    state: directory
    path: /etc/rancher/rke2
    owner: root
    group: root
    mode: 0755

- name: Set server taints
  ansible.builtin.set_fact:
    combined_node_taints: "{{ rke2_server_node_taints }}"
  when: rke2_type == 'server'

- name: Set agent taints
  ansible.builtin.set_fact:
    combined_node_taints: "{{ rke2_agent_node_taints }}"
  when: rke2_type == 'agent'

- name: Copy RKE2 config
  ansible.builtin.template:
    src: "{{ rke2_config }}"
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: 0644

- name: Copy Containerd Registry Configuration file
  ansible.builtin.template:
    src: "{{ rke2_custom_registry_path }}"
    dest: /etc/rancher/rke2/registries.yaml
    owner: root
    group: root
    mode: 0644
  when: rke2_custom_registry_mirrors.0.endpoint | length > 0

- name: Start RKE2 service on the rest of the nodes
  ansible.builtin.systemd:
    name: "rke2-{{ rke2_type }}.service"
    state: started
    enabled: true
    no_block: true
  environment:
    RKE2_TOKEN: "{{ rke2_token }}"

- name: Mask other RKE2 service on the rest of the nodes
  ansible.builtin.systemd:
    name: "rke2-{{ item }}.service"
    enabled: false
    masked: true
  with_items:
    - "{{ (['agent', 'server'] | reject('match', rke2_type) | list) }}"
